petstagram/photos/urls.py
from django.urls import path, include
from petstagram.photos import views


urlpatterns =[
    path('add/', views.add_photo, name='add_photo'),
    path('<int:photo_pk>/', include([
        path('', views.details_photo, name='details_photo'),
        path('edit/', views.edit_photo, name='edit_photo'),
        path('delete/', views.delete_photo, name='delete_photo'),
    ]))
]

petstagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from petstagram import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.common.urls'), name='common'),
    path('accounts/', include('petstagram.accounts.urls')),
    path('pets/', include('petstagram.pets.urls')),
    path('photos/', include('petstagram.photos.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petstagram/photos/models.py
from django.db import models
from django.core.validators import MinLengthValidator

from petstagram.pets.models import Pet
from petstagram.photos.validators import ImageSizeValidator

# Create your models here.

class Photo(models.Model):
    photo = models.ImageField(
        upload_to='media/',
        validators=[ImageSizeValidator(5, 'MB', 'The maximum image size can that be uploaded is 5Mb.')]
    )

    description = models.TextField(
        max_length=300,
        validators=[MinLengthValidator(10)],
        null=True,
        blank=True,
    )

    location = models.CharField(
        max_length=30,
        default='not selected'
    )

    tagged_pets = models.ManyToManyField(
        to=Pet,
        blank=True,
        related_name='tagged_pets'  # should've named it better tagged_photos idk
    )

    date_of_publication = models.DateField(
        auto_now=True,
    )

    def __str__(self) -> str:
        return str(self.pk)

petstagram/photos/forms.py
from django import forms

from petstagram.photos.models import Photo


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = '__all__'


class EditPhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        exclude = ['photo']

petstagram/photos/views.py
from lib2to3.fixes.fix_input import context

from django.shortcuts import render, redirect

from petstagram.common.forms import CommentForm
from petstagram.photos.forms import CreatePhotoForm, EditPhotoForm
from petstagram.photos.models import Photo


# Create your views here.

def add_photo(request):
    form = CreatePhotoForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('home-page')

    context = {'form': form}
    return render(request, 'photos/photo-add-page.html', context=context)


def details_photo(request, photo_pk):
    photo_obj = Photo.objects.filter(pk=photo_pk).first()
    likes = photo_obj.likes_photo.all()
    comments = photo_obj.comments_photo.all()
    comment_form = CommentForm()

    if photo_obj:
        context = {
            'photo_obj': photo_obj,
            'likes': likes,
            'comments': comments,
            'comment_form': comment_form
        }

        return render(request, 'photos/photo-details-page.html', context)

    return render(request, 'common/home-page.html')


def edit_photo(request, photo_pk):
    photo = Photo.objects.get(pk=photo_pk)
    form = EditPhotoForm(request.POST or None, request.FILES or None, instance=photo)
    if form.is_valid():
        form.save()
        return redirect('details_photo', photo_pk)

    context = {'form': form}
    return render(request, 'photos/photo-edit-page.html', context=context)


def delete_photo(request, photo_pk):
    photo = Photo.objects.get(pk=photo_pk)
    photo.delete()
    return redirect('home-page')

templates/photos/photo-add-page.html
{% extends "common/base.html" %}

{% block content %}
    <!-- Start Add Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <!-- Start Add Photo Form -->
        <form action="post" enctype="multipart/form-data">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>
            <!-- Add Photo Button -->
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
        <!-- End Add Photo Form -->
    </div>
    <!-- End Add Photo Section -->
    
{% endblock %}

templates/photos/photo-details-page.html
{% extends "common/base.html" %}

{% block content %}
    <div class="container">
        <div class="col-9">
            {% comment %} send queryset of one photo to pet-posts {% endcomment %}
            <!-- Start Pet Photo Post Section -->
            <div class="card">
                <div class="top">

                    <!-- Start User Details and Image Location Section -->
                    <div class="userDetails">

                        <!-- Link to User Profile Details Page-->
                        <a href="#">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <img src="/static/images/person.png" alt="img8">
                                    </div>
                                </div>
                            </div>
                        </a>
                        <h3>

                            <!-- Link to User Profile Details Page -->
                            <a href="#">
                                <!-- IF user has first name and last name -->
                                Diyan Kalaydzhiev
                                <!-- else -->
                                <!-- show user username -->
                            </a>
                            <br>

                            <!-- IF the photo has location -->
                            <span>Bansko, Bulgaria</span>

                            <!-- IF the viewer is the creator of the photo -->
                            <div class="edit-delete-btns">

                                <!-- Link to Edit Pet Photo Page -->
                                <a href="#">
                                    <img class="edit-img" src="/static/images/edit-pen-icon-6.jpg"
                                        alt="edit button">
                                </a>

                                <!-- Link to Delete Pet Photo Page -->
                                <a href="#">
                                    <img class="bin-img" src="/static/images/icon-remove-22.jpg" alt="bin button">
                                </a>
                            </div>
                            <!-- End IF the viewer is the creator of the photo -->

                        </h3>
                    </div>
                    <!-- End User Details and Image Location Section -->

                </div>

                <!-- Start Pet Photo -->
                <div class="imgBx" id="place the id of the photo here">
                    <!-- Pet Photo -->
                    <img src="/static/images/axolotl.jpeg" alt="post" class="cover">
                </div>
                <!-- End Pet Photo -->

                <div class="bottom">

                    <!-- Start Like and Share Buttons Section -->
                    <div class="actionBtns">
                        <div class="left">

                            <!-- Start Like Button -->
                            <span class="heart">

                                    <!-- Link to Like Path -->
                                    <a href="#">
                                        <!-- if user has liked the photo -->
                                        <!-- <i class="fa-solid fa-heart" style="color: #ed4040;"></i> -->
                                        <!-- else -->
                                        <i class="fa-regular fa-heart"></i>
                                    </a>
                            </span>
                            <!-- End Like Button -->

                            <!-- Start Share  Button -->

                            <!-- Link to Share Path -->
                            <a href="#">
                                <i class="fa-solid fa-share"></i>
                            </a>
                        </div>
                    </div>
                    <!-- End Like and Share Buttons Section -->

                    <!-- Number of Likes for the Photo -->
                    <p class="likes">203 likes</p>

                    <!-- Start Tagged Pets Section-->
                    <!-- Link to First Tagged Pet Details Page -->
                    <a href="#">
                        <p class="message">
                            <b>Sasho</b>
                        </p>
                    </a>
                    <!-- Link to Second Tagged Pet Details Page -->
                    <a href="#">
                        <p class="message">
                            <b>Some other fish</b>
                        </p>
                    </a>
                    <!-- End Tagged Pets Section-->

                    <!-- Photo description -->
                    <p class="pet-details">This is my pet</p>

                    <!-- Date of Publication or edit of the Photo -->
                    <h5 class="postTime">19/09/2022</h5>

                    <!-- Start Comments Section -->
                    <div class="comments">
                        <div class="top">
                            <div class="userDetails">
                                <div class="comment-data">
                                    <div class="profilepic">
                                        <div class="profile_img">
                                            <div class="image">
                                                <!-- User Profile Image -->
                                                <img src="/static/images/person.png" alt="img8">
                                            </div>
                                        </div>
                                    </div>
                                    <p>
                                        <!-- Link to User Profile Details Page-->
                                        <!-- User First and/or Last Name or username-->
                                        <a href="">Steven Ivanov</a>
                                        <!-- User Comment -->
                                        - OMG where can i get one
                                    </p>
                                </div>
                                <span>Sept. 20, 2022, 5:02 p.m.</span>
                            </div>
                        </div>
                    </div>
                    <!-- End Comments Section -->
                </div>

                <!-- Start Add Comments Section -->
                <div class="addComments">

                    <!-- Start Add Comments Form -->
                    <form method="post" action="#">
                        <label for="id_body">Body:</label>
                        <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                                  required="" id="id_body"></textarea>
                        <!-- Post Comments Button -->
                        <button type="submit">Post</button>
                    </form>
                    <!-- End Add Comments Form -->

                </div>
                <!-- End Add Comments Section -->

            </div>
            <!-- End Pet Photo Post Section -->

        </div>
    </div>

{% endblock %}

templates/photos/photo-edit-page.html
{% extends "common/base.html" %}

{% block content %}
    <!-- Starts Edit Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <!-- Starts Edit Photo Form -->
        <form action="">

            <p>
                <label for="id_description">Description:</label>
                <input type="text" value="Sasho is an Axolotl">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"
                    value="Bansko, Bulgaria">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option selected>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>

            <!-- Edit Photo Button -->
            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>
        <!-- End Edit Photo Form -->

    </div>
    <!-- End Edit Photo Section -->

{% endblock %}